- name: copy app.ini for RedHat
  copy:
       src: ./files/app.ini
       dest: /srv/simple-python-app/
       owner: nginx
       group: nginx
       mode: u=rw,g=r,o=r


- name: copy wsgi.py for RedHat
  copy:
       src: ./files/simple-python-app.service
       dest: /etc/systemd/system/simple-python-app.service
       owner: root
       group: root
       mode: u=rw,g=r,o=r

- name: Patch uwsgi.ini for RedHat
  copy:
       src: files/uwsgi.ini
       dest: /etc/uwsgi.ini
       owner: root
       group: root
       mode: 0644


- name: copy nginx site config for RedHat
  copy:
       src: ./files/nginx.conf
       dest: /etc/nginx/
       owner: root
       group: root
       mode: u=rw,g=r,o=r

