- name: Create a virtual environment
  command: "python3 -m venv /srv/simple-python-app"

- name: Install requirements.txt
  command: "'/srv/simple-python-app/bin/pip' install -r '/srv/simple-python-app/requirements.txt'"

- name: flask db upgrade
  shell: flask db upgrade
  args:
    chdir: /srv/simple-python-app/